### ISSUE TITLE
Slot content cannot be conditionally shown (toggled) more than once

### ISSUE THREAD

**Issue by CommanderQ** [salesforce/lwc#1409]
### Description

When using a slotted component with conditionally-displayed content (using an `if` directive), the content can be displayed and hidden successfully once (a show -> hide cycle), but subsequent attempts to show -> hide the content do not work, generating an error in the console:
> engine.js:5002 Uncaught (in promise) TypeError: Cannot redefine property: nodeValue at defineProperties (<anonymous>) at patchElementWithRestrictions (VM39 engine.js:5002) at createElmHook (VM39 engine.js:5085) at Object.create (VM39 engine.js:5299) at createChildrenHook (VM39 engine.js:5168) at Object.insert (VM39 engine.js:5309) at createChildrenHook (VM39 engine.js:5169) at Object.insert (VM39 engine.js:5309) at updateStaticChildren (VM39 engine.js:2108) at patchChildren (VM39 engine.js:4596)

#### Steps to Reproduce

[This playground](https://developer.salesforce.com/docs/component-library/tools/playground/g996Gsc72/2/edit) has a consistent repro of the issue and instructions for the few button clicks required. :smile:

#### Expected Results

Slotted contents shown / hidden any number of times.

#### Actual Results
Slotted contents are only shown / hidden once, generating an exception on all subsequent attempts.

### Browsers Affected
Tested on Chrome and Firefox

### Version

- LWC: v0.40.1-222.6 and later

**Comment by caridy** [comment]
@CommanderQ first of all, my dream is to get all reported issue with the level of this one, this is a great repro case. As for the bug itself, I believe this is not longer a case with master branch, but we will have to validate that. @jodarove can you take this one?

**Comment by CommanderQ** [comment]
Woo hoo! 😄 I'm even happier that it's an issue that's likely already fixed - thank you @caridy !

**Comment by caridy** [comment]
@jodarove and I will be validating this today.

**Comment by jodarove** [comment]
Hi @CommanderQ just verified that your repro steps are already fixed in the master branch. Thanks for reporting this issue!

**Comment by mattgoldspink** [comment]
@caridy We just hit this in our LWC's in orgs. Do you know when this will Salesforce orgs?

**Comment by caridy** [comment]
I believe it will be there soon. @Gr8Gatsby can you provide a timeline for this? @jodarove can you confirm that this fix is in patch?

**Comment by caridy** [comment]
@jodarove can you confirm that this was cherry picked?

**Comment by nathanfigueroaguidewire** [comment]
@caridy @CommanderQ @jodarove This issue persists as of API 48.0

**Comment by nfig-gw** [comment]
> @caridy @CommanderQ @jodarove This issue persists as of API 48.0

After further digging this issue appears to be limited. I'm experiencing this issue with [LightningButtonGroup](https://github.com/salesforce/base-components-recipes/tree/master/force-app/main/default/lwc/buttonGroup), it may be due to the way this component handles its own slotted content.

**Comment by jodarove** [comment]
@nfig-gw this particular issue is fixed in spring20 (48) you can see it fine in this playground: https://developer.salesforce.com/docs/component-library/tools/playground/otwQSE_PK/1/edit

however, i remember fixing a similar issue 17 days ago in https://github.com/salesforce/lwc/pull/1787 (arrives with summer20)

Can provide some repro steps? We will want to take a look and fix the recipes.

**Comment by nfig-gw** [comment]
Thanks @jodarove #1787 looks very similar to my issue. Here are the steps to reproduce and a sandbox: 

1. Create a child component with a slot that conditionally hides its slotted content
2. Pass a LightningButtonGroup into the child component
3. Toggle the hide/show of your child's slotted content. The LightningButtonGroup will not reappear after being hidden.

Demo: https://developer.salesforce.com/docs/component-library/tools/playground/YtJWuyVFg/19/edit
